# Generated by Django 3.2.5 on 2021-08-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
