# Generated by Django 3.2.5 on 2021-08-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
