# Generated by Django 3.2.5 on 2021-08-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20210810_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
